import networkx as nx
import matplotlib.pyplot as plt
from collections import Counter

SFG = nx.Graph()
SFG.add_node('E0', intensity=10., type='E', mz=0 )
SFG.add_node('E1', intensity=10., type='E', mz=1 )
SFG.add_node('E2', intensity=10., type='E', mz=2 )
SFG.add_node('E3', intensity=10., type='E', mz=3 )
SFG.add_node('E4', intensity=10., type='E', mz=4 )
SFG.add_node('E5', intensity=10., type='E', mz=5 )
SFG.add_node('I0', intensity=.1, type='I' )
SFG.add_node('I1', intensity=.1, type='I' )
SFG.add_node('I2', intensity=.1, type='I' )
SFG.add_node('I3', intensity=.1, type='I' )
SFG.add_node('I4', intensity=.1, type='I' )
SFG.add_node('I5', intensity=.1, type='I' )
SFG.add_node('I6', intensity=.1, type='I' )
SFG.add_node('M0', type='M' )
SFG.add_node('M1', type='M' )
SFG.add_node('M2', type='M' )
SFG.add_edge('E0','I0')
SFG.add_edge('E0','I4')
SFG.add_edge('E1','I0')
SFG.add_edge('E1','I4')
SFG.add_edge('E2','I1')
SFG.add_edge('E2','I5')
SFG.add_edge('E2','I2')
SFG.add_edge('E3','I2')
SFG.add_edge('E3','I5')
SFG.add_edge('E4','I3')
SFG.add_edge('E4','I6')
SFG.add_edge('E5','I3')
SFG.add_edge('E5','I6')
SFG.add_edge('E5','I6')
SFG.add_edge('I0','M0')
SFG.add_edge('I1','M0')
SFG.add_edge('I2','M1')
SFG.add_edge('I3','M1')
SFG.add_edge('I4','M2')
SFG.add_edge('I5','M2')
SFG.add_edge('I6','M2')
